apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-api-gateway
  labels:
    app: petclinic-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-api-gateway
  template:
    metadata:
      labels:
        app: petclinic-api-gateway
    spec:
      containers:
        - name: petclinic-api-gateway
          image: 440744236722.dkr.ecr.ap-south-1.amazonaws.com/petclinic-api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://petclinic-discovery-service:8761/eureka/"
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-api-gateway-service
spec:
  selector:
    app: petclinic-api-gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

